### ISSUE TITLE
implement proper tests for matching / applying patterns and so on

### ISSUE THREAD

**Issue by hoechp** [fujaba/org.fujaba.graphengine#12]
need tests for
- [x] #9 finding a match for a pattern on a graph
- [x] #9 finding all matches for a pattern on a graph
- [x] #9 applying actions on a match
- [x] #9 cycle-free repetitive application of patterns and their actions
- [x] #8 comparison to SDMLib wherever possible
