### ISSUE TITLE
implement requested changes from meeting 4

### ISSUE THREAD

**Issue by hoechp** [fujaba/org.fujaba.graphengine#13]
![20161208_182104](https://cloud.githubusercontent.com/assets/23620495/21020495/09a9e934-bd75-11e6-9989-fc2ed2fd3fbd.jpg)
- [x] #14 unify 'action' and 'negative' attributes of patterns in 'action'-attribute with value "+", "-", "==" (= default), "!="
- [x] #15 implement ReachabilityGraph features
- [x] #16 attribute conditions must become much more powerful, probably a conjunctive normal form of attribute conditions using some sort of expression library or otherwise sufficiant expressions
- [x] #17 implement some sort of visualization like with alchemy.js or d3.js (see graphviz.org, yuml.me)
- [x] #18 don't mess with overridden 'equals' or 'compareTo', unless with 'hashcode', too. and only if it should be necessary - which it currently ain't. so remove redefinitions!
- [x] #19 fix faulty handling of negative nodes
- [ ] #8 maybe test some more performance when the rest is kinda done
